
package ee.ttu.idu0075.cyclingresults.wsdl;


import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Random;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "DiplomaService", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", wsdlLocation = "file:/Users/kaspar/IdeaProjects/cyclingresults/src/main/resources/DiplomaService.xsd")
public class DiplomaService extends Service {

    private final static URL DIPLOMASERVICE_WSDL_LOCATION;
    private final static WebServiceException DIPLOMASERVICE_EXCEPTION;
    private final static QName DIPLOMASERVICE_QNAME = new QName("http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", "DiplomaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/kaspar/IdeaProjects/cyclingresults/src/main/resources/DiplomaService.xsd");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIPLOMASERVICE_WSDL_LOCATION = url;
        DIPLOMASERVICE_EXCEPTION = e;
    }

    public DiplomaService() {
        super(__getWsdlLocation(), DIPLOMASERVICE_QNAME);
    }

    public DiplomaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIPLOMASERVICE_QNAME, features);
    }

    public DiplomaService(URL wsdlLocation) {
        super(wsdlLocation, DIPLOMASERVICE_QNAME);
    }

    public DiplomaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIPLOMASERVICE_QNAME, features);
    }

    public DiplomaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DiplomaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns DiplomaPortType
     */
    @WebEndpoint(name = "DiplomaPort")
    public DiplomaPortType getDiplomaPort() {
        return super.getPort(new QName("http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", "DiplomaPort"), DiplomaPortType.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DiplomaPortType
     */
    @WebEndpoint(name = "DiplomaPort")
    public DiplomaPortType getDiplomaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", "DiplomaPort"), DiplomaPortType.class, features);
    }

    @WebEndpoint
    public CompetitorType addCompetitor(AddCompetitorRequest request) {
        CompetitorType competitor = new CompetitorType();
        if (request.getToken().equalsIgnoreCase("secrettoken123")) {
            competitor.setId(new Random().nextLong());
            competitor.setName(request.getName());
            competitor.setPersonalCode(request.getPersonalCode());
            return competitor;
        }
        return null;
    }

    private static URL __getWsdlLocation() {
        if (DIPLOMASERVICE_EXCEPTION != null) {
            throw DIPLOMASERVICE_EXCEPTION;
        }
        return DIPLOMASERVICE_WSDL_LOCATION;
    }

}
