
package ee.ttu.idu0075.cyclingresults.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "DiplomaPortType", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface DiplomaPortType {


    /**
     * @param parameter
     * @return returns ee.ttu.idu0075.cyclingresults.wsdl.DiplomaType
     */
    @WebMethod
    @WebResult(name = "addDiplomaResponse", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
    public DiplomaType addDiploma(
            @WebParam(name = "addDiplomaRequest", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
                    AddDiplomaRequest parameter);

    /**
     * @param parameter
     * @return returns ee.ttu.idu0075.cyclingresults.wsdl.FindAllDiplomasResponse
     */
    @WebMethod
    @WebResult(name = "findAllDiplomasResponse", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
    public FindAllDiplomasResponse findAllDiplomas(
            @WebParam(name = "findAllDiplomasRequest", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
                    FindAllDiplomasRequest parameter);

    /**
     * @param parameter
     * @return returns ee.ttu.idu0075.cyclingresults.wsdl.FindDiplomaByIdResponse
     */
    @WebMethod
    @WebResult(name = "findDiplomaByIdResponse", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
    public FindDiplomaByIdResponse findDiplomaById(
            @WebParam(name = "findDiplomaByIdRequest", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
                    FindDiplomaByIdRequest parameter);

    /**
     * @param parameter
     * @return returns ee.ttu.idu0075.cyclingresults.wsdl.DiplomaType
     */
    @WebMethod
    @WebResult(name = "setCompetitorToDiplomaResponse", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
    public DiplomaType setCompetitorToDiploma(
            @WebParam(name = "setCompetitorToDiplomaRequest", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
                    SetCompetitorToDiplomaRequest parameter);

    /**
     * @param parameter
     * @return returns ee.ttu.idu0075.cyclingresults.wsdl.FindAllCompetitorsWithDiplomasResponse
     */
    @WebMethod
    @WebResult(name = "findAllCompetitorsWithDiplomasResponse", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
    public FindAllCompetitorsWithDiplomasResponse findAllCompetitorsWithDiplomas(
            @WebParam(name = "findAllCompetitorsWithDiplomasRequest", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
                    FindAllCompetitorsWithDiplomasRequest parameter);

    /**
     * @param parameter
     * @return returns ee.ttu.idu0075.cyclingresults.wsdl.CompetitorType
     */
    @WebMethod
    @WebResult(name = "addCompetitorResponse", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
    public CompetitorType addCompetitor(
            @WebParam(name = "addCompetitorRequest", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
                    AddCompetitorRequest parameter);

    /**
     * @param parameter
     * @return returns ee.ttu.idu0075.cyclingresults.wsdl.FindAllCompetitorsResponse
     */
    @WebMethod
    @WebResult(name = "findAllCompetitorsResponse", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
    public FindAllCompetitorsResponse findAllCompetitors(
            @WebParam(name = "findAllCompetitorsRequest", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
                    FindAllCompetitorsRequest parameter);

    /**
     * @param parameter
     * @return returns ee.ttu.idu0075.cyclingresults.wsdl.FindCompetitorByIdResponse
     */
    @WebMethod
    @WebResult(name = "findCompetitorByIdResponse", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
    public FindCompetitorByIdResponse findCompetitorById(
            @WebParam(name = "findCompetitorByIdRequest", targetNamespace = "http://www.ttu.ee/idu0075/2018/ws/cyclingresults/wsdl", partName = "parameter")
                    FindCompetitorByIdRequest parameter);

}
